CREATE DATABASE `wsign` /*!40100 DEFAULT CHARACTER SET utf8 */;

DROP TABLE IF EXISTS `wsign`.`userinfo`;
CREATE TABLE  `wsign`.`userinfo` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=111112 DEFAULT CHARSET=utf8;